### ISSUE TITLE
About joint features after loading urdf

### ISSUE THREAD

**Issue by ChicyChen** [haosulab/SAPIEN#40]
I have loaded 167th model's urdf, in which, for example, the initial joint feature is
```
<joint name="joint_1" type="continuous">
		<origin xyz="0 -0.4051616942026166 -0.18586969420261662"/>
		<axis xyz="1 0 0"/>
		<child link="link_1"/>
		<parent link="link_2"/>
	</joint>
```
```
<joint name="joint_3" type="continuous">
		<origin xyz="-0.0015881912962019719 0 -0.18586980870379802"/>
		<axis xyz="0 1 0"/>
		<child link="link_3"/>
		<parent link="link_2"/>
	</joint>
```
However, then I do `print(j.type)` and `np.rad2deg(t3d.euler.quat2euler(j.get_pose_in_parent().q))`, 
which for joint_1 gives type `revolute` and:
`[ 1.80000000e+02 -0.00000000e+00 -2.03555475e-12]`  = [180, 0, 0]
which for joint_3 gives type `revolute` and:
`[-9.00000000e+01 -3.41509397e-06  9.00000000e+01]` = [-90, 0, 90]
By default, in a urdf file, I guess origin rpy should be `[0,0,0]`, why would the two joint have different get_pose_in_parent result and why is the joint type changed?
Thanks a lot!

**Comment by fbxiang** [comment]
There is no continuous joint in SAPIEN since continuous joint is equivalent to revolute joint with no joint limit. And that is exactly the representation used in SAPIEN. 
The `j.get_pose_in_parent` returns a pose assuming `x` is the joint axis. You can note the <axis> tag and <origin> tag actually provides redundant information in URDF and SAPIEN will  combine them. You should also note there are multiple equivalent transformations in a link-joint-link pair, so the joint pose will not be unique, but the `x` axis of the joint frame will always be the same since this is no ambiguity here (that is where the joint axis is pointing at).
