### ISSUE TITLE
ImportError of Sapien2.0

### ISSUE THREAD

**Issue by JYChen18** [haosulab/SAPIEN#50]
**System:**
 - OS version: [Ubuntu 18.04]
 - Python version (if applicable): [Python 3.7]
 - SAPIEN version (pip freeze | grep sapien): 2.0a0
 - Environment: [Desktop]

**Describe the bug**
I want to import sapien2 and get the ImportError below.

Traceback (most recent call last):
  File "xxxxxx.py", line 1, in <module>
    import sapien.core as sapien
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/sapien/__init__.py", line 1, in <module>
    from sapien import core, sensor, asset, example, utils
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/sapien/core/__init__.py", line 1, in <module>
    from .pysapien import *
ImportError: libvulkan.so.1: cannot open shared object file: No such file or directory

**To Reproduce**
1.  pip install sapien==2.0a0
2. python
>>> import sapien.core as sapien

**Additional context**
I can correctly import sapien1.1.1 by the same way, but failed with sapien2.0a0.

**Comment by fbxiang** [comment]
SAPIEN 2.0 has excluded the vulkan library from distribution since we find out it is a very bad idea to package it. libvulkan.so.1 typically comes with the graphics driver or the system (usually located at `/usr/lib/x86_64-linux-gnu/libvulkan.so.1`). If it is missing, maybe you can try to install the `libvulkan1` package.
