### ISSUE TITLE
KuaFu active light sensor may fail to sense the surface if the .obj mesh file material is very blue

### ISSUE THREAD

**Issue by ray8828** [haosulab/SAPIEN#88]
Hi, thanks for sharing this great work, I'm using the active ligth sensor to generate some data, but I found that when my obj file contain very blue material, i.e. the `.mtl` file has some color like `Kd 0.0 0.0 0.4`, both left and right IR image will be nothing on this object, and depth is invalid, but when i change the material to other colors like pure black  `Kd 0.0 0.0 0.0` or red  `Kd 1.0 0.0 0.0` the depth works fine.

Could you give me some sense why this would happens? Thanks!
RGB
<img width="127" alt="image" src="https://user-images.githubusercontent.com/26106300/190938594-e6fa1a00-563c-4af3-9c62-5addc066bfbf.png">

Dep
<img width="103" alt="image" src="https://user-images.githubusercontent.com/26106300/190938608-40f19602-bfa1-4b32-a65f-477294d99362.png">

IR
<img width="113" alt="image" src="https://user-images.githubusercontent.com/26106300/190938613-35282fd9-c745-4fb3-a7ee-3f245f283330.png">

**Comment by ray8828** [comment]
playing with this issue, I found that pure green material also can get a bad IR reflectance, only when the red component is not zero or pure black can give a good reflectance IR pattern

**Comment by fbxiang** [comment]
I believe Kuafu active light only uses the red component, since real sensors uses infrared lights, and since simulators never use full-spectrum materials, and infrared material is also almost never provided, the closest thing is to use the red component as the infrared reflectance.
In the real-world, if you find something that only reflects green or blue lights (of course this almost never happens), realsense will not be able to sense its depth. So this behavior in Kuafu is intended.

**Comment by ray8828** [comment]
Thanks! I see, this is reasonable. I resolved this issue by adding slightly a little red component to the material in the database
